username: <>
password: <>
phone_number: <>

profile_path: 'https://www.linkedin.com/in/gulnazds/' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- Junior Data Scientist
- Data Analyst
- entry level data scientist 


locations:
- London
- Remote
- United Kingdom

salary: 40,000
rate: 25
# --------- Optional Parameters -------
uploads:
  Resume: Data_Scientist_Gulnaz.pdf
  Cover Letter: cover_letter_GB.pdf
  #Photo: # PATH TO photo


output_filename:
- out.csv

# blacklist:
# - # Company names you want to ignore

experience_level:
  - Entry level
  - Associate
  - Internship
